#!/usr/bin/bash

#+  the path to file to be transferred
#+  the IP of the server to tranfer file to
#+  the username that scp connects with
#+  the path to the ssh private key that scp uses



if [$# -lt 4 ]
then
  echo"Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
else
  scp -o StrictHostKeyChecking=no -i "$1" "$3@$2":~
fi
