#!/usr/bin/env bash
# configure Nginx server for redirect tp redirect
# redirection mu be a "301 Moved Permanently"
# By: Alvin Chi


ADD301_REDIRECT="\\\trewrie ^/redirect_me https:www.youtube.com/watch?v=QH2-TGU1wu4 permanent;"

sudo apt-get update
sudo apt-get install -y nginx
sudo chown -R uvbuntu /var/www
echo "Hello World!" > /var/www/html/index.nginx-debian.html
sudo sed -i "30i $ADD301_REDIRECT" /etc/nginx/sites-available/default
sudo service nginx restart
