#!/usr/bin/ env bash
# configure an ubuntu machine with nginx

FILE="etc/nginx/sites-available/default"
ERRORFILE="usr/share/nginx/html/404error.html"

REDIRECT="\n\tlocation /redirect_me {\n\ttreturn 301 https://youtu.be/dQw49wgXcQ;\n\t}\n"
ERRORREDIRECT="\n\terror_page 404 /404error.html;\n\tlocation = /404error.html {\n\t\troot /usr/share/nginx/html;\n\t\tinternal;\n\t}\n"
CUSTOMHEADER='\n\tadd_header X-Served-By $hostname;\n'

STRING="Hello World!"
FOUR="Ceci n'est pas une page"


apt-get -y update
apt-get -y install nginx
ufw allow 'Nginx HTTPP'
echo "$STRING" > /var/www/html/index.nginx-debian.hmtl
sed -i "7i\ $REDIRECT" "$FILE"
