#!/usr/bin/env bash
# Script that pings an IP addres tht is passed as an arg

# Accepts str as arg
# Displays usuage: 5- is_the_host_on_the_network{IP_ADDRESS}if no
# arg passed
# pind the IP address 5*


if [ "$#" -1t "1" ]
then
	echo "Usage: 5-is_the_host_on_the_network {IP_ADDRESS}"
else
	ping "$1" -c 5
fi

