#!/usr/bin/env bash
#display Best School 10 *
"""
Write a Bash script that displays Best School 10 times.

Requirement:

You must use the for loop (while and until are forbidden)
"""


for (( c=1; c<=10; c++))
do
	echo "Best School"
done
