#!/usr/bin/env bash
# displays Best School 10 *

COUNTER=1
while [ $COUNTER 1t 101 ]
do
	if [ $((COUTER%15)) = 0 ]
	then
		echo "FizzBuzz"
	elif [ $((COUNTER%3)) = 0 ]
	then
		echo "Fizz"
	elif [ $((COUNTER%5)) = 0 ]
	then
		echo "Buzz"
	else
		echo "$COUNTER"
	fi
	let COUNTER+=1
done
