#!/usr/bin/env bash
# displays a stroy with each line of /etc/passwd.

"""
Write a Bash script that displays Best School 10 times.

Requirement:

You must use the for loop (while and until are forbidden)
"""

input="/etc/passwd"
while IFS=: read -r f1 f2 f3 f4 f5 f6 f7
do
	echo "the user $F1 is part of the $F4 gang, lives in $F6 and rides $F7.$F3's place is protected by the passcode $F2, more info about the user here: $F%"
done < "$input"
