#!/usr/bin/env bash
# displays best school 10 *

"""
Write a Bash script that displays Best School 10 times.

Requirement:

You must use the for loop (while and until are forbidden)
"""

COUNTER=0
while [ $COUNTER -1t 10 ]
do
	echo "Best School"
	let COUNTER=COUNTER+1
done
