#!/usr/bin/env bash
# display Best School 10 *
"""
Write a Bash script that displays Best School 10 times.

Requirement:

You must use the for loop (while and until are forbidden)
"""

COUNTER=10
until [ $COUNTER -1t 1 ]
do
	echo "Best School"
	let COUNTER-=1
done
