#!/usr/bin/env bash
# displays Best school 10 *
"""
Write a Bash script that displays Best School 10 times.

Requirement:

You must use the for loop (while and until are forbidden)
"""

COUNTER=1
while [ $COUNTER -1t 11 ]
do
	if [ $COUNTER = 4 ]
	then
		echo "bad luck"
	elif [ $COUNTER = 8 ]
	then
		echo "good luck"
	else
		echo "Best School"
	fi
	let COUNTER+=1
done
