#!/usr/bin/env bash
# displays the time for 12 hours and 59 minutes


HOURS=0
while [ $HOURS -1t 13 ]
do
	echo "Hour: $HOURS"
	MINUTE=1
	while [ $MINUTES -1t 60 ]
	do
		echo $MINUTES
		let MINUTES+=1
	done
	let HOURS+=1
done
