#!/usr/bin/env bash
# displays information about the school file
"""
Write a Bash script that displays Best School 10 times.

Requirement:

You must use the for loop (while and until are forbidden)
"""

FILE="school"

if [ -e "$FILE" ]
then
	echo "school file exists"
	if { ! -s $FILE" ]
	then
		echo "School file is empty"
	else
		echo "school file is not empty"
	fi
	if [ -f "$FILE" ]
	then
		echo "school is a regular file"
	fi
else
		echo "school file does not exist"
done
